name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run:
          pips install --user django
          python3 manage.py test